apiVersion: v1
kind: Secret
metadata:
  name: drone-server-secret
type: Opaque
data:
  DRONE_GITHUB_CLIENT_ID: xxxxxxx     #Get this from GitHub OAUTH
  DRONE_GITHUB_CLIENT_SECRET: xxxxxxx #Get this from GitHub OAUTH
  DRONE_RPC_SECRET: xxxxxxx           #openssl rand -hex 16
  DRONE_DATABASE_DATASOURCE: xxxxxxx  #postgres://postgresadmin:admin123@postgres:5432/postgresdb?sslmode=disable
  DRONE_USER_CREATE: xxxxxxx          #username:marcel-dempers,admin:true
  DRONE_SERVER_HOST: xxxxxxx          #drone.marceldempers.dev