apiVersion: apps/v1
kind: Deployment
metadata:
  name: testenodemonitor
spec:
  selector:
    matchLabels:
      app: testenodemonitor
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: testenodemonitor
    spec:
      containers:
      - name: testenodemonitor
        image: luismartorano/testenodemonitor:v1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: testenodemonitor
  labels:
    app: testenodemonitor
spec:
  type: ClusterIP
  selector:
    app: testenodemonitor
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 5000
