apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: testenodemonitor
  namespace: default
  
spec:
  endpoints:
  - interval: 30s
    port: web
  selector:
    matchLabels:
      app: testenodemonitor
