---
apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: default
  annotations:
    vault.hashicorp.com/tls-skip-verify: "true"
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'webapp'
    vault.hashicorp.com/agent-inject-secret-config.txt: 'kv/dev/apps/service01'      
spec:
  containers:
  - image: nginx:latest
    name: nginx
  serviceAccountName: vault-auth