apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'webapp'
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        vault.hashicorp.com/agent-inject-secret-config.txt: 'kv/dev/apps/service01'
        vault.hashicorp.com/agent-inject-template-config.txt: |
          {{ with secret "kv/dev/apps/service01" }}
          [DEFAULT]
          LogLevel = DEBUG
          [DATABASE]
          Address=127.0.0.1
          Port=3306
          User={{ .Data.data.appkey }}
          Password={{ .Data.data.apptoken }}
          Database=app
          {{ end }}
      labels:
        app: nginx
    spec:
      serviceAccountName: vault-auth
      containers:
        - name: nginx
          image: nginx:latest